# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-expt',
                'doc_host': 'https://amod99.github.io',
                'git_url': 'https://github.com/amod99/nbdev-expt',
                'lib_path': 'nbdev_expt'},
  'syms': {'nbdev_expt.core': {'nbdev_expt.core.foo': ('core.html#foo', 'nbdev_expt/core.py')}}}
